### PR TITLE
Use HTML tests for OTR

### PR DESCRIPTION
**Pull request by rcchan**
Allows testserver to run OTR tests

### CODE REVIEW

**Comment by adhintz** [comment]
Ryan, thanks for all of the pull requests! I'll start reviewing them.

**Comment by rcchan** [comment]
#263 is the final product of its dependencies and contains the OTR AKE integration tests that I used to diagnose a lot of the issues.  Naturally, it has a humongous diff but that should boil down to just the tests once the other PRs are merged in.

**Comment by adhintz** [comment]
Sounds good, thanks. What are you using to run the tests? ./do.sh testserver doesn't currently include /otr/ but we can add it.

Running the tests internally, the tests in /otr/ work fine. However tests in subdirectories such as /otr/message/ are failing because genjsdeps.sh isn't creating a test_js_deps-runfiles.js file in /otr/message/

**Comment by rcchan** [comment]
`./do.sh testserver` should include `/otr/` once this patch is applied.  It just seems to pick up anything `*_test.html`?

I'm seeing it when I load up `localhost:8000` and it's included in both the test file list and running all tests

**Comment by adhintz** [comment]
You're right. I was looking at the wrong git client -- one that didn't have your patch.

I fixed the internal test and your patch runs fine.

**Pull request merged**
