### PR TITLE
Allow CTR mode counter to overflow until it cycles

### LINKED ISSUE #198: Incorrect rollover error for counter mode
Ctr mode throws an error if after incrementing the nonce it becomes zero.  This is for the purpose of preventing reuse of nonces but only does so if the nonce had started at 0. It has the effect of limiting the amount of blocks that can be encrypted to (2^32) - nonce. Xoring the counter to nonce would solve the issue, though the error might not be needed as since most other modes have much lower safe limits (due to birthday problem) limiting the amount of data that is encrypted is already something that must be handled higher up.

### PR DESCRIPTION
**Pull request by rcchan**
Fixes #198

### CODE REVIEW

**Comment by adhintz** [comment]
LGTM, but I'll ask @thaidn to double-check as it changes crypto.

**Comment by thaidn** [comment]
Two comments:
* Can you test this against more NIST SP 800-38A test vectors?
* It's a bad design to allow callers to specify the IV. You will have to ensure that each time you call e2e.ciphermode.Ctr.prototype.encryptSync, the IV is correctly generated. Why don't you generate a random IV in e2e.ciphermode.Ctr.prototype.encryptSync?

**Comment by rcchan** [comment]
`.encrypt` is inherited from [ciphermode](https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/ciphermode/ciphermode.js) which specifies an IV parameter.

`.encryptSync` performs the encrypt operation minus wrapping in an async `Result`.

**Comment by rcchan** [comment]
Additional tests added in #284

**Comment by rcchan** [comment]
Rebuild CI

**Comment by koto** [comment]
@thaidn, some more test vectors have been added in 7fa39bb1cce553ce39c42af5eebb7aac46d2fe1d. As for IV, Ryan is right - we use this design for all other ciphermodes.

**Pull request merged**
