### PR TITLE
Abort keyring restore

### LINKED ISSUE #224: backup key window abort key missing
bild 2015-01-28 um 10 26 58

there is no possibility to leave this window!

I like the idea, but usability + setup is incredible bad!!
Btw. this looks like a part-time-one-day-a-week project of Google?

### PR DESCRIPTION
**Pull request by rcchan**
Closes #224

### CODE REVIEW

**Comment by rcchan** [comment]
Try CI rebuild

**Comment by rcchan** [comment]
CI errors appear to be inside closure-library... Local tests are passing.  Can someone confirm error/success?

**Comment by adhintz** [comment]
I've opened an issue with closure-compiler here: https://github.com/google/closure-compiler/issues/904

**Comment by rcchan** [comment]
Rebuild CI

**Pull request merged**
